export const ActionTypes = {
  //USER CONSTANTS
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  //CART CONSTANTS
  SET_CART: "SET_CART",
  INCREMENT_QTY: "INCREMENT_QTY",
  DECREMENT_QTY: "DECREMENT_QTY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  //PRODUCT CONSTANTS
  SET_PRODUCTS: "SET_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  SET_CATEGORY: "SET_CATEGORY",
  SET_SORT: "SET_SORT",
};
